### ISSUE TITLE
refactoring to use queries

### ISSUE THREAD

**Issue by jeetelongname** [jcs-elpa/ts-fold#1]
Hello! 
I am currently working on intergrating tree sitter into [doom emacs](https://github.com/hlissner/doom-emacs/pull/5401) and I was writing a code forlding plugin for it, after I had gotten most of it done someone notified me of this package which made a lot of that work redundant. 

The only problem I have is that the way you handle the "getting" of the range. its not terribly idiomatic compared to some other examples [evil-textobj-tree-sitter](https://github.com/meain/evil-textobj-tree-sitter), [emacs-tree-sitter proper](https://github.com/emacs-tree-sitter/tree-sitter-langs) as well as all of the nvim tree sitter efforts, this makes this package an outlier in this regard.

I was wondering if you could provide some insight into why you have gone this route and if you would be open to a refactor which I can then work on. 

Thanks! 
Jeet

**Comment by jeetelongname** [comment]
Ok Ill have a look at the code. and start work on a PR

**Comment by jcs090218** [comment]
I have tried to go for this route, see #5 for progress.

**Comment by jeetelongname** [comment]
Hi sorry for my silence on the matter, I will start testing and see if there is anything to change, where did you get the queries for this? It should be said that nvim tree sitter uses a custom predicate called `#make-range!` which does not exist in emacs tree sitter

**Comment by jcs090218** [comment]
No worries! I was busy working on something else as well. :)

I got the queries directly from [evil-textobj-tree-sitter](https://github.com/meain/evil-textobj-tree-sitter) repo. But like as I mentioned above, I would need to work on learning s-expression, which I am not very good at! Can you help me simplify those query files?

**Comment by jeetelongname** [comment]
Hi Jcs,

Yeah I can look into them, nvim also has folding so it might be good to take
those instead but ill look into it and provide a proper PR

Regards,
– *Jeetaditya Chatterjee*
/Sent using my text editor/

**Comment by jcs090218** [comment]
I may have come to the conclusion, the queries implementation is simply too slow (Windows). If someone want to try it out, see #5.
