### ISSUE TITLE
Ruby spec files folding support

### ISSUE THREAD

**Issue by alexshgov** [jcs-elpa/ts-fold#25]
Folding works correctly in general `.rb` files, however, does not work in `_spec.rb` files for some reasons.
No errors in the log.

Testing on spacemacs build running on `GNU Emacs 28.1 (build 1, x86_64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.6 (Build 20G165)) of 2022-07-18 [2 times]`

**Comment by jcs090218** [comment]
Hmm... I could do it in `_spec.rb`. Does the `tree-sitter` parse the source file correctly? 😕 We might need more information to debug this bug...?

**Comment by jcs090218** [comment]
Hmm... I could do it in `_spec.rb`. Does the `tree-sitter` parse the source file correctly? 😕 We might need more information to debug this bug...?

**Comment by alexshgov** [comment]
@jcs090218 I've recorded a video, see

https://user-images.githubusercontent.com/9149289/183890061-db1414f8-6656-4a2d-93e2-3e5683c3c2cc.mov

**Comment by jcs090218** [comment]
Can you post the code here as well (not working one)? It would be easier for us to debug! Thanks! ❤️

**Comment by x3qt** [comment]
I am having the same issue whith specs, as you may see on a screenshot no folding regions are detected here:
![image](https://user-images.githubusercontent.com/1782826/183962287-3eaebcc8-7857-45f3-bcbd-622237eb206b.png)

```ruby
# frozen_string_literal: true

require 'spec_helper'

RSpec.describe UseCase do
  describe '#call' do
  end
end
```

```ruby
class UseCase
  def call
  end
end
```

Messages emacs messages log
```
Local variables list is not properly terminated
Loading /Users/yuryp/.spacemacs...done
Package ‘all-the-icons’ isn’t installed
Loading /Users/yuryp/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
Wrote /Users/yuryp/.emacs.d/recentf
[rbenv] Using the currently activated ruby.
Starting new Ispell process /usr/local/bin/ispell with default dictionary...done
Spacemacs is ready.
Loading /Users/yuryp/.emacs.d/.cache/recentf...done
Skipping check for new version (reason: dotfile)
Package cl is deprecated
Wrote /Users/yuryp/.emacs.d/.cache/recentf
Loading /Users/yuryp/.emacs.d/.cache/recentf...done
[yas] Prepared just-in-time loading of snippets successfully.
tsc-dyn-get: Using source :github (:loaded nil :recorded 0.18.0 :requested 0.18.0)
tsc-dyn-get: Recorded version already satifies requested -> loading
Auto-evilification could not remap these functions in map ‘archive-mode-map’:
   - ‘archive-chgrp-entry’ originally mapped on ‘G’
Auto-evilification could not remap these functions in map ‘tar-mode-map’:
   - ‘tar-chgrp-entry’ originally mapped on ‘G’
[tree-sitter-langs] Running (git rev-parse --show-toplevel) in /Users/yuryp/.emacs.d/elpa/28.1/develop/tree-sitter-langs-20220508.636/
The directory /Users/yuryp/.emacs.d/elpa/28.1/develop/tree-sitter-langs-20220508.636/ doesn’t seem to be a git working dir. Grammar-building functions will not work.
tree-sitter-langs: Grammar bundle v0.12.0 was already installed; skipped
[rbenv] using 3.0.0
[rbenv] Using ruby version from .ruby-version file.
Search failed: there is an unmatched expression somewhere or we are at the beginning/end of file. [2 times]
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
[rbenv] Using the currently activated ruby.
Indenting region...done
ad-Advice-delete-backward-char: Beginning of buffer [3 times]
evil-line-move: Beginning of buffer
Error: (user-error "No foldable node found at POS")
Auto-saving...
evil-line-move: End of buffer [5 times]
evil-find-char: Can’t find G
auto trimmed 0 chars

```

**Comment by x3qt** [comment]
Important note: I use an integration through https://develop.spacemacs.org/layers/+tools/tree-sitter/README.html, so in my layers is following:
```elisp
     (tree-sitter :variables
           tree-sitter-fold-enable t)
```

**Comment by jcs090218** [comment]
Ahh, okay. I think I got it.

The title of this issue is a bit misleading. I thought the issue was caused by **spec** file but apparently we never support `do_block` node in the Ruby parser. That's why it would never fold! Should be added in #26.

I have also added support for if/else block, and while/for loop. Hope this package works a bit better with Ruby. 😅

**Comment by alexshgov** [comment]
> 

Thanks for your quick replies @jcs090218 !

**Comment by x3qt** [comment]
Now works, thanks a lot! 🚀
